version: '3'
services:
  web:
    build: .
    command: 'jupyter notebook --no-browser --port=${PORT} --ip=0.0.0.0 --allow-root --NotebookApp.password="sha1:6f50777b9654:d7be130f413745989835eb88241683e7078e2857"'
    ports:
     - "${PORT}:${PORT}"
    expose:
     - "${PORT}"
    volumes:
    - ./:/app


#